SUPABASE_URL=https://bozuqgvzlonzbwqiujzo.supabase.co
SUPABASE_PUBLISHABLE_KEY=sb_publishable_X_yRnrd_3dVTI0k9LFDWtQ_c_SiACjs
SUPABASE_SECRET_KEY=sb_secret_H273f-kzSOBdKR_81QzPVA_w5F7rrFW
SUPABASE_JWKS_URL=https://bozuqgvzlonzbwqiujzo.supabase.co/auth/v1/.well-known/jwks.json
